Fix compilation error
Fix following error: `error[E0599]: no method named
`to_primitive_values` found for struct `pnet_base::MacAddr` in
the current scope`.

See https://github.com/libpnet/libpnet/issues/361 for possible cause.